# Generated by Django 5.1.13 on 2026-09-22 13:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import forge.common.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=140, validators=[forge.common.fields.validate_no_html])),
                ('description', models.TextField(blank=True, max_length=2000, validators=[forge.common.fields.validate_no_html])),
                ('due_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('delivered', 'Delivered'), ('dropped', 'Dropped')], default='planned', max_length=12)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('external_url', models.URLField(blank=True, help_text='If the team tracks this work elsewhere, link to it rather than keeping two boards in step by hand.', validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'due_on', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=3000, validators=[forge.common.fields.validate_no_html])),
                ('blockers', models.TextField(blank=True, help_text='What is in the way. Leaving this blank week after week while nothing ships helps nobody.', max_length=1500, validators=[forge.common.fields.validate_no_html])),
                ('needs_help', models.BooleanField(default=False, help_text='Flags this update to the mentor and to community leads. Asking for help early is the behaviour the platform wants to reward.')),
                ('covers_week_of', models.DateField(default=django.utils.timezone.localdate)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='projects.project')),
            ],
            options={
                'ordering': ['-covers_week_of', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160, validators=[forge.common.fields.validate_no_html])),
                ('description', models.TextField(blank=True, max_length=4000, validators=[forge.common.fields.validate_no_html])),
                ('status', models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('in_review', 'In review'), ('done', 'Done'), ('dropped', 'Dropped')], db_index=True, default='todo', max_length=12)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High')], default=2)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_reason', models.CharField(blank=True, help_text='Required when a task is blocked. A blocked task nobody can see the reason for is a task that stays blocked.', max_length=300)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='workspace.milestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'ordering': ['-priority', 'due_on', 'created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='workspace_t_project_d21a30_idx'), models.Index(fields=['assignee', 'status'], name='workspace_t_assigne_91f5b5_idx')],
            },
        ),
    ]
