# Generated by Django 5.1.13 on 2026-09-22 13:06

import django.db.models.deletion
import django.utils.timezone
import forge.common.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_id', models.CharField(max_length=64)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(choices=[('harassment', 'Harassment or abuse'), ('academic_dishonesty', 'Academic dishonesty'), ('misattribution', "Passing off another's work as one's own"), ('unsafe_security', 'Unsafe or unlawful security activity'), ('spam', 'Spam or advertising'), ('off_topic', 'Off topic or low quality'), ('privacy', 'Personal data shared without consent'), ('other', 'Something else')], max_length=24)),
                ('detail', models.TextField(max_length=2000, validators=[forge.common.fields.validate_no_html])),
                ('status', models.CharField(choices=[('open', 'Open'), ('triaged', 'Triaged'), ('escalated', 'Escalated to the faculty advisor'), ('upheld', 'Upheld'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=12)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, max_length=2000, validators=[forge.common.fields.validate_no_html])),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_assigned', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('note', 'Note on file, no action'), ('warn', 'Warning issued'), ('remove_content', 'Content removed'), ('lock_thread', 'Thread locked'), ('suspend', 'Member suspended'), ('remove_from_project', 'Removed from a project'), ('refer_to_university', 'Referred to the University')], max_length=24)),
                ('rationale', models.TextField(help_text='Required. Every moderation decision on FORGE is explainable, including to the person it was taken against.', max_length=2000, validators=[forge.common.fields.validate_no_html])),
                ('expires_at', models.DateTimeField(blank=True, help_text='For a time-limited suspension. An indefinite suspension needs the faculty advisor.', null=True)),
                ('notified_subject_at', models.DateTimeField(blank=True, null=True)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_received', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='moderation.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcceptableUseAcceptance',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.CharField(default='acceptable_use', max_length=40)),
                ('version', models.CharField(max_length=16)),
                ('text_digest', models.CharField(help_text='SHA-256 of the exact text accepted.', max_length=64)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'document', 'version'), name='uniq_acceptance')],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='moderation__status_282342_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['target_type', 'target_id'], name='moderation__target__ba1da2_idx'),
        ),
    ]
