"""
Levels, badges, leaderboards and certificates.

Section 10 of the concept proposal is blunt about the stakes: a voluntary
platform with no recognition empties by the third trimester, and one with
badly designed recognition fills with worthless activity. Three design
choices here follow from that.

**Recognition is computed from the ledger, never entered by hand.** There is
no field anywhere that an administrator can set to give somebody a level.

**Leaderboards are per discipline area and per period.** A single global
board would be won permanently by whoever writes the most code, and a Nursing
or Education student would never appear on it. Snapshots are taken per
trimester so that a strong contributor from two years ago does not occupy the
top of the board forever, which is the other way these boards go dead.

**A certificate states what was done, not how good it was.** FORGE awards no
academic credit and issues nothing that could be mistaken for a University
qualification; the wording of every certificate has to keep that true.
"""

from __future__ import annotations

import secrets

from django.conf import settings
from django.db import models
from django.utils import timezone

from forge.common.models import BaseModel, ImmutableModel, UUIDModel


class Level(BaseModel):
    """
    A named standing. Seeded from section 10.4 of the proposal.

    `requires_teaching` marks the top level: the highest standing is reserved
    for those who have both delivered and taught, which is what stops the
    ladder from being a pure output count.
    """

    name = models.CharField(max_length=40, unique=True)
    slug = models.SlugField(max_length=40, unique=True)
    rank = models.PositiveSmallIntegerField(unique=True)
    min_points = models.PositiveIntegerField()
    min_confirmed_contributions = models.PositiveSmallIntegerField(default=0)
    min_completed_projects = models.PositiveSmallIntegerField(default=0)
    requires_teaching = models.BooleanField(
        default=False,
        help_text="Requires confirmed contributions in the mentorship dimension.",
    )
    description = models.TextField(blank=True)

    class Meta:
        ordering = ["rank"]

    def __str__(self) -> str:
        return self.name


class Standing(BaseModel):
    """
    A member's current recognition state. Derived; safe to rebuild from scratch.

    Recomputed whenever a ledger entry settles. Everything in it can be
    regenerated by `python manage.py rebuild_standings`, which matters because
    a derived table that cannot be rebuilt is a derived table that will
    eventually be wrong and unfixable.
    """

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                related_name="standing")
    level = models.ForeignKey(Level, null=True, blank=True, on_delete=models.SET_NULL,
                              related_name="holders")
    total_points = models.PositiveIntegerField(default=0, db_index=True)
    confirmed_contributions = models.PositiveIntegerField(default=0)
    completed_projects = models.PositiveIntegerField(default=0)
    projects_led = models.PositiveIntegerField(default=0)
    people_mentored = models.PositiveIntegerField(default=0)
    points_by_dimension = models.JSONField(default=dict, blank=True)
    points_by_area = models.JSONField(default=dict, blank=True)
    first_contribution_at = models.DateTimeField(null=True, blank=True)
    last_contribution_at = models.DateTimeField(null=True, blank=True)
    recomputed_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ["-total_points"]

    def __str__(self) -> str:
        return f"{self.user.display_name}: {self.total_points} points"


class LevelAward(BaseModel):
    """When a member reached a level. Kept so the portfolio can show a trajectory."""

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                             related_name="level_awards")
    level = models.ForeignKey(Level, on_delete=models.CASCADE, related_name="awards")
    points_at_award = models.PositiveIntegerField()
    awarded_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ["-awarded_at"]
        constraints = [models.UniqueConstraint(fields=["user", "level"],
                                               name="uniq_level_award")]

    def __str__(self) -> str:
        return f"{self.user.display_name} reached {self.level.name}"


class Badge(BaseModel):
    """
    A specific, earned marker.

    Badges are for things a points total cannot express: finishing a first
    project, mentoring somebody to their first delivery, working across
    schools, keeping a project alive through a whole trimester. `criteria` is
    published so that nobody has to guess how one is earned -- an unexplained
    badge is a popularity prize with extra steps.
    """

    class Kind(models.TextChoices):
        MILESTONE = "milestone", "Milestone"
        CRAFT = "craft", "Craft"
        COMMUNITY = "community", "Community"
        STEWARDSHIP = "stewardship", "Stewardship"

    name = models.CharField(max_length=60, unique=True)
    slug = models.SlugField(max_length=60, unique=True)
    kind = models.CharField(max_length=16, choices=Kind.choices, default=Kind.MILESTONE)
    description = models.CharField(max_length=240)
    criteria = models.CharField(max_length=300,
                                help_text="Published on the badge. Say exactly how it is earned.")
    icon = models.CharField(max_length=40, blank=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ["kind", "name"]

    def __str__(self) -> str:
        return self.name


class BadgeAward(BaseModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                             related_name="badge_awards")
    badge = models.ForeignKey(Badge, on_delete=models.CASCADE, related_name="awards")
    project = models.ForeignKey("projects.Project", null=True, blank=True,
                                on_delete=models.SET_NULL, related_name="badge_awards")
    reason = models.CharField(max_length=300, blank=True)
    awarded_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ["-awarded_at"]
        constraints = [models.UniqueConstraint(fields=["user", "badge", "project"],
                                               name="uniq_badge_award")]

    def __str__(self) -> str:
        return f"{self.user.display_name}: {self.badge.name}"


class LeaderboardSnapshot(BaseModel):
    """
    A frozen board for one scope and one period.

    Computed on a schedule rather than on demand. A live board recomputed on
    every page view is both the platform's most expensive query and its most
    addictive feature, and neither is something to encourage.
    """

    class Scope(models.TextChoices):
        DISCIPLINE = "discipline", "Discipline area"
        COMMUNITY = "community", "Community contribution"
        MENTORSHIP = "mentorship", "Mentorship"
        OVERALL = "overall", "Overall"

    class Period(models.TextChoices):
        TRIMESTER = "trimester", "Trimester"
        YEAR = "year", "Year"
        ALL_TIME = "all_time", "All time"

    scope = models.CharField(max_length=12, choices=Scope.choices)
    discipline_area = models.ForeignKey("accounts.DisciplineArea", null=True, blank=True,
                                         on_delete=models.CASCADE, related_name="leaderboards")
    period = models.CharField(max_length=10, choices=Period.choices,
                              default=Period.TRIMESTER)
    period_start = models.DateField()
    period_end = models.DateField()
    rows = models.JSONField(default=list,
                            help_text="[{rank, user_id, display_name, public_slug, points, "
                                      "contributions}]")
    computed_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ["-period_end", "scope"]
        constraints = [
            models.UniqueConstraint(fields=["scope", "discipline_area", "period",
                                            "period_start"],
                                    name="uniq_leaderboard_snapshot")
        ]

    def __str__(self) -> str:
        label = self.discipline_area.name if self.discipline_area else self.get_scope_display()
        return f"{label} {self.period_start}..{self.period_end}"


class Certificate(UUIDModel):
    """
    A verifiable certificate of participation.

    Every certificate carries a code that anyone can check at
    /api/v1/recognition/certificates/verify/<code>/ without an account. A
    certificate that cannot be independently checked is a PDF, and a PDF is
    something anybody can make.

    `statement` is rendered at issue and stored, so that the wording a member
    was given is the wording that is verified later, even if the template
    changes.
    """

    class Kind(models.TextChoices):
        PARTICIPATION = "participation", "Participation in a project"
        COMPLETION = "completion", "Completion of a delivered project"
        MENTORSHIP = "mentorship", "Mentorship"
        COMMUNITY = "community", "Community contribution"

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                             related_name="certificates")
    kind = models.CharField(max_length=16, choices=Kind.choices)
    project = models.ForeignKey("projects.Project", null=True, blank=True,
                                on_delete=models.SET_NULL, related_name="certificates")
    recipient_name = models.CharField(max_length=160)
    statement = models.TextField(max_length=1200)
    verification_code = models.CharField(max_length=24, unique=True, db_index=True)
    ledger_head = models.CharField(
        max_length=64, blank=True,
        help_text="The ledger hash at the moment of issue, tying the certificate "
                  "to a point in the verifiable record.",
    )
    issued_at = models.DateTimeField(default=timezone.now)
    revoked_at = models.DateTimeField(null=True, blank=True)
    revoked_reason = models.CharField(max_length=300, blank=True)

    class Meta:
        ordering = ["-issued_at"]

    def __str__(self) -> str:
        return f"{self.get_kind_display()} -- {self.recipient_name}"

    @staticmethod
    def new_code() -> str:
        """A human-transcribable code: no ambiguous characters."""
        alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
        raw = "".join(secrets.choice(alphabet) for _ in range(12))
        return f"{raw[:4]}-{raw[4:8]}-{raw[8:]}"

    @property
    def is_valid(self) -> bool:
        return self.revoked_at is None

    @property
    def download_count(self) -> int:
        return self.downloads.count()

    @property
    def last_downloaded_at(self):
        first = self.downloads.first()  # ordered newest first
        return first.downloaded_at if first else None


class CertificateDownload(UUIDModel, ImmutableModel):
    """
    A record of each time a certificate PDF was produced.

    Two reasons this exists, and only the second was asked for.

    The holder gets an audit trail of their own document: when it was taken
    and how many copies are out there. If a certificate they downloaded once
    shows four downloads, something is wrong with their account rather than
    with the certificate.

    And because every downloaded copy is stamped with the moment it was issued
    (see `pdf.py`), a leaked or altered copy can be traced back to a specific
    download rather than to "somebody, at some point".

    Append-only, like everything else that is evidence.
    """

    certificate = models.ForeignKey(Certificate, on_delete=models.CASCADE,
                                    related_name="downloads")
    downloaded_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL,
        related_name="certificate_downloads",
    )
    downloaded_by_name = models.CharField(
        max_length=160, blank=True,
        help_text="Denormalised so the trail survives the account being erased.",
    )
    was_holder = models.BooleanField(
        default=True,
        help_text="False when a steward took a copy on the member's behalf.",
    )
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    user_agent = models.CharField(max_length=300, blank=True)
    downloaded_at = models.DateTimeField(default=timezone.now, db_index=True)

    class Meta:
        ordering = ["-downloaded_at"]
        indexes = [models.Index(fields=["certificate", "-downloaded_at"])]

    def __str__(self) -> str:
        return f"{self.certificate.verification_code} by {self.downloaded_by_name or 'unknown'}"
