# Generated by Django 5.1.13 on 2026-09-22 13:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import forge.accounts.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineArea',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('level', models.CharField(choices=[('certificate', 'Certificate'), ('diploma', 'Diploma'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('doctoral', 'Doctoral')], default='undergraduate', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['school__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='University email address. Used to establish that you are a genuine member of the University.', max_length=254, unique=True)),
                ('recovery_email', models.EmailField(blank=True, help_text='A personal address that will still work after you graduate. Without it you will lose access to your portfolio when your University address is withdrawn.', max_length=254)),
                ('full_name', models.CharField(max_length=160)),
                ('preferred_name', models.CharField(blank=True, max_length=80)),
                ('public_slug', models.SlugField(help_text='The stable address of your public portfolio. Choose carefully: changing it breaks links you have already shared.', max_length=40, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9]([a-z0-9-]{1,38}[a-z0-9])$', 'Use 3 to 40 characters: lowercase letters, numbers and hyphens, not starting or ending with a hyphen.')])),
                ('kind', models.CharField(choices=[('student', 'Student'), ('staff', 'Academic or administrative staff'), ('alumnus', 'Alumnus'), ('external', 'External mentor or partner')], default='student', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending email verification'), ('active', 'Active'), ('alumnus', 'Graduated or deprovisioned'), ('suspended', 'Suspended'), ('closed', "Closed at the member's request")], db_index=True, default='pending', max_length=12)),
                ('year_of_study', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('headline', models.CharField(blank=True, max_length=140)),
                ('bio', models.TextField(blank=True, max_length=2000)),
                ('location', models.CharField(blank=True, help_text='County or town. Optional, and never finer than that.', max_length=80)),
                ('links', models.JSONField(blank=True, default=dict, help_text='Optional: {"github": "...", "linkedin": "...", "site": "..."}')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/')),
                ('portfolio_is_public', models.BooleanField(default=True, help_text='A public portfolio is the point of FORGE, but it remains your choice. Turning this off hides the public page; it does not delete anything.')),
                ('show_email_on_portfolio', models.BooleanField(default=False)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('oidc_subject', models.CharField(blank=True, db_index=True, help_text='Subject claim from University single sign-on, when in use.', max_length=255)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deprovisioned_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_conduct_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_conduct_version', models.CharField(blank=True, max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('interests', models.ManyToManyField(blank=True, related_name='interested_members', to='accounts.disciplinearea')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.programme')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.school')),
            ],
            options={
                'ordering': ['full_name'],
            },
            managers=[
                ('objects', forge.accounts.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='programme',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to='accounts.school'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('usage_count', models.PositiveIntegerField(default=0, editable=False)),
                ('discipline_areas', models.ManyToManyField(blank=True, related_name='skills', to='accounts.disciplinearea')),
            ],
            options={
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('self_rating', models.PositiveSmallIntegerField(choices=[(1, 'Learning'), (2, 'Working knowledge'), (3, 'Strong')], default=1)),
                ('wants_to_learn', models.BooleanField(default=False, help_text='Marks this as a skill you want to practise. Role matching weighs it, so beginners are offered a way in rather than only ever being matched to what they already know.')),
                ('evidence_count', models.PositiveIntegerField(default=0, editable=False)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='accounts.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-evidence_count', 'skill__name'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('recovery_email', 'Recovery address'), ('reverification', 'Annual re-verification')], default='registration', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'consumed_at'], name='accounts_em_user_id_c04489_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoleGrant',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('mentor', 'Mentor'), ('community_lead', 'Community lead'), ('faculty_advisor', 'Faculty advisor'), ('moderator', 'Moderator'), ('platform_maintainer', 'Platform maintainer')], max_length=32)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for an open-ended grant. Student-held roles should normally expire at the end of a trimester and be renewed.', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('discipline_area', models.ForeignKey(blank=True, help_text='Where the role is scoped to one area, for example a community lead for Health.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_grants', to='accounts.disciplinearea')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_granted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-granted_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('user', 'role', 'discipline_area'), name='uniq_active_role_grant')],
            },
        ),
        migrations.AddConstraint(
            model_name='programme',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uniq_programme_per_school'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status', 'kind'], name='accounts_us_status_8941aa_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_seen_at'], name='accounts_us_last_se_39c8f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='userskill',
            constraint=models.UniqueConstraint(fields=('user', 'skill'), name='uniq_user_skill'),
        ),
    ]
