# Generated by Django 5.1.13 on 2026-09-22 18:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Set when the platform generated the password. The member is held at the change-password screen until they choose their own, so a credential that has travelled through email does not stay valid.'),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_recovery_email',
            field=models.EmailField(blank=True, help_text="An address that has been submitted but not yet confirmed. Kept separate so the interface can say 'we are waiting on you' rather than showing nothing and looking broken.", max_length=254),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=160)),
                ('kind', models.CharField(choices=[('student', 'Student'), ('staff', 'Academic or administrative staff'), ('alumnus', 'Alumnus'), ('external', 'External mentor or partner')], default='student', help_text="What sort of account this creates. Anything other than 'student' is exempt from the University domain check, which is the whole reason invitations exist.", max_length=12)),
                ('role', models.CharField(blank=True, choices=[('mentor', 'Mentor'), ('community_lead', 'Community lead'), ('faculty_advisor', 'Faculty advisor'), ('moderator', 'Moderator'), ('platform_maintainer', 'Platform maintainer')], help_text='A standing role granted on acceptance. Optional.', max_length=32)),
                ('message', models.TextField(blank=True, help_text='Included in the email. An invitation from a stranger with no context reads like spam and gets treated as spam.', max_length=1000)),
                ('invited_by_name', models.CharField(blank=True, max_length=160)),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked'), ('expired', 'Expired')], db_index=True, default='pending', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.PositiveSmallIntegerField(default=1)),
                ('last_sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_used', to=settings.AUTH_USER_MODEL)),
                ('discipline_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='accounts.disciplinearea')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('email',), name='uniq_pending_invitation_per_email')],
            },
        ),
    ]
