# Generated by Django 5.1.13 on 2026-09-22 13:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioExport',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_format', models.CharField(choices=[('json', 'Signed JSON'), ('data_request', 'Full personal data export')], default='json', max_length=16)),
                ('document_digest', models.CharField(help_text='SHA-256 of the exact document issued.', max_length=64)),
                ('signature', models.TextField(blank=True)),
                ('key_id', models.CharField(blank=True, max_length=64)),
                ('ledger_head', models.CharField(blank=True, max_length=64)),
                ('entry_count', models.PositiveIntegerField(default=0)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_exports_requested', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['document_digest'], name='portfolio_p_documen_b591d3_idx')],
            },
        ),
    ]
