# Generated by Django 5.1.13 on 2026-09-22 13:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import forge.common.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=160, validators=[forge.common.fields.validate_no_html])),
                ('about', models.TextField(max_length=2000, validators=[forge.common.fields.validate_no_html])),
                ('capacity', models.PositiveSmallIntegerField(default=2, help_text='How many projects you are willing to mentor at once. Set this honestly and low. Nobody is served by a mentor who has agreed to more than they can do.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('availability', models.CharField(choices=[('open', 'Accepting requests'), ('limited', 'At capacity'), ('paused', 'Not available at the moment')], default='open', max_length=10)),
                ('hours_per_month', models.PositiveSmallIntegerField(blank=True, help_text='Indicative. Shown to students so they ask for a realistic amount.', null=True, validators=[django.core.validators.MaxValueValidator(200)])),
                ('is_alumnus', models.BooleanField(default=False)),
                ('organisation', models.CharField(blank=True, max_length=160)),
                ('discipline_areas', models.ManyToManyField(blank=True, related_name='mentors', to='accounts.disciplinearea')),
                ('expertise', models.ManyToManyField(blank=True, related_name='mentors', to='accounts.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__full_name'],
            },
        ),
        migrations.CreateModel(
            name='OfficeHour',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('capacity', models.PositiveSmallIntegerField(default=1)),
                ('topic', models.CharField(blank=True, max_length=200, validators=[forge.common.fields.validate_no_html])),
                ('joining_url', models.URLField(blank=True, help_text='Shared with attendees only, once they have booked.')),
                ('is_cancelled', models.BooleanField(default=False)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_hours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipRequest',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(help_text="What you are working on and what you would like help with. A specific ask gets a reply; 'be my mentor' usually does not.", max_length=1500, validators=[forge.common.fields.validate_no_html])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=12)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField(blank=True, max_length=1000, validators=[forge.common.fields.validate_no_html])),
                ('expires_at', models.DateTimeField(blank=True, help_text='Requests lapse rather than sitting unanswered forever. A student left waiting with no answer concludes the platform is dead.', null=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_requests_received', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_requests', to='projects.project')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('requester', 'mentor', 'project'), name='uniq_pending_mentorship_request')],
            },
        ),
        migrations.CreateModel(
            name='OfficeHourBooking',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(blank=True, max_length=1000, validators=[forge.common.fields.validate_no_html])),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('attended', models.BooleanField(blank=True, null=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_hour_bookings', to=settings.AUTH_USER_MODEL)),
                ('office_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='mentorship.officehour')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True)), fields=('office_hour', 'attendee'), name='uniq_office_hour_booking')],
            },
        ),
    ]
