# Generated by Django 5.1.13 on 2026-09-22 13:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import forge.common.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=140, validators=[forge.common.fields.validate_no_html])),
                ('slug', forge.common.fields.AutoSlugField(blank=True, editable=False, max_length=160, populate_from='title', unique=True)),
                ('summary', models.CharField(help_text='One or two sentences. This is what appears in listings.', max_length=300, validators=[forge.common.fields.validate_no_html])),
                ('problem_statement', models.TextField(help_text='What problem does this address, and for whom?', max_length=4000, validators=[forge.common.fields.validate_no_html])),
                ('objectives', models.TextField(help_text='What will exist at the end that does not exist now? Be concrete: these are the objectives your delivery will be reviewed against.', max_length=4000, validators=[forge.common.fields.validate_no_html])),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('target_completion_on', models.DateField(blank=True, help_text='An indicative date. Nothing punishes you for missing it; it exists so that a teammate knows what they are agreeing to.', null=True)),
                ('effort_hours_per_week', models.PositiveSmallIntegerField(blank=True, help_text="Expected of each team member. Most FORGE members are studying at a distance and many are in employment -- say honestly what this will cost someone's week.", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for review'), ('under_review', 'Under review'), ('returned', 'Returned for revision'), ('declined', 'Declined'), ('recruiting', 'Recruiting a team'), ('building', 'In build'), ('in_review', 'In review and testing'), ('documenting', 'Documenting and demonstrating'), ('completed', 'Completed'), ('archived', 'Archived'), ('abandoned', 'Abandoned')], db_index=True, default='draft', max_length=16)),
                ('visibility', models.CharField(choices=[('university', 'Visible across the University'), ('public', 'Visible to anyone, including employers')], default='university', max_length=12)),
                ('is_listed', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_open_source', models.BooleanField(default=False, help_text='Releasing work openly is encouraged and never required. A member who intends to commercialise their work keeps that right.')),
                ('licence', models.CharField(blank=True, help_text='For example MIT, Apache-2.0, CC-BY-4.0. Required if the project is marked open.', max_length=40)),
                ('repository_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('ownership_agreed_at', models.DateTimeField(blank=True, help_text='When the team recorded how ownership of the work is shared. Agreed at the outset, not at the point of success.', null=True)),
                ('ownership_terms', models.TextField(blank=True, help_text='How the team has agreed to share ownership of what they create.', max_length=2000, validators=[forge.common.fields.validate_no_html])),
                ('discipline_areas', models.ManyToManyField(related_name='projects', to='accounts.disciplinearea')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects_led', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(blank=True, help_text='The mentor who reviews delivery and countersigns contributions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_mentored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectReview',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('returned', 'Returned for revision'), ('declined', 'Declined')], max_length=12)),
                ('scope_is_realistic', models.BooleanField(default=True)),
                ('is_lawful_and_ethical', models.BooleanField(default=True)),
                ('is_not_duplicative', models.BooleanField(default=True)),
                ('has_clear_objectives', models.BooleanField(default=True)),
                ('reasons', models.TextField(help_text='Required for every decision, including approval. A proposal declined without reasons teaches the student nothing.', max_length=3000, validators=[forge.common.fields.validate_no_html])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='projects.project')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_reviews', to=settings.AUTH_USER_MODEL)),
                ('suggested_mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_for_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, validators=[forge.common.fields.validate_no_html])),
                ('description', models.TextField(max_length=2000, validators=[forge.common.fields.validate_no_html])),
                ('slots', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('is_open', models.BooleanField(default=True)),
                ('open_to_beginners', models.BooleanField(default=False, help_text='Marks this as a role a first-year with no track record can take. Every project is encouraged to carry at least one.')),
                ('preferred_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_roles', to='accounts.school')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='projects.project')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='required_by_roles', to='accounts.skill')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_lead', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('left_reason', models.CharField(blank=True, max_length=255)),
                ('understudy_to', models.ForeignKey(blank=True, help_text='The member this person is shadowing, so that the role survives their departure. The proposal commits every leadership role to carrying an identified understudy; this is where that is recorded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='understudies', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.project')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='projects.projectrole')),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement', models.TextField(help_text='Why this role, and what you would bring to it. Two paragraphs is plenty.', max_length=1500, validators=[forge.common.fields.validate_no_html])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, help_text='Required when declining. A student who is turned down without a reason learns nothing and is less likely to apply again.', max_length=1000, validators=[forge.common.fields.validate_no_html])),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_decided', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projects.project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projects.projectrole')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StageTransition',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for review'), ('under_review', 'Under review'), ('returned', 'Returned for revision'), ('declined', 'Declined'), ('recruiting', 'Recruiting a team'), ('building', 'In build'), ('in_review', 'In review and testing'), ('documenting', 'Documenting and demonstrating'), ('completed', 'Completed'), ('archived', 'Archived'), ('abandoned', 'Abandoned')], max_length=16)),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for review'), ('under_review', 'Under review'), ('returned', 'Returned for revision'), ('declined', 'Declined'), ('recruiting', 'Recruiting a team'), ('building', 'In build'), ('in_review', 'In review and testing'), ('documenting', 'Documenting and demonstrating'), ('completed', 'Completed'), ('archived', 'Archived'), ('abandoned', 'Abandoned')], max_length=16)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_transitions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', '-last_activity_at'], name='projects_pr_status_56e4bf_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['lead', 'status'], name='projects_pr_lead_id_fa69f9_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('left_at__isnull', True)), fields=('project', 'user'), name='uniq_active_membership'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted'])), fields=('role', 'applicant'), name='uniq_live_application_per_role'),
        ),
    ]
