# Generated by Django 5.1.13 on 2026-09-22 13:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(max_length=4000)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('send_email', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('digest_frequency', models.CharField(choices=[('immediate', 'Email me as things happen'), ('daily', 'One email a day'), ('weekly', 'One email a week'), ('off', 'No email -- I will check the site')], default='daily', max_length=10)),
                ('muted_categories', models.JSONField(blank=True, default=list)),
                ('quiet_hours_start', models.TimeField(blank=True, default=None, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verb', models.CharField(db_index=True, max_length=48)),
                ('category', models.CharField(choices=[('project', 'Your projects'), ('application', 'Applications and team formation'), ('contribution', 'Contributions and confirmations'), ('community', 'Discussions you follow'), ('mentorship', 'Mentorship'), ('recognition', 'Levels, badges and certificates'), ('moderation', 'Conduct and moderation'), ('platform', 'Platform announcements')], db_index=True, default='platform', max_length=16)),
                ('summary', models.CharField(max_length=300)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('included_in_digest_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_caused', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('target_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='notificatio_recipie_ce9d56_idx'), models.Index(fields=['recipient', 'category'], name='notificatio_recipie_6bdf81_idx')],
            },
        ),
    ]
