# Generated by Django 5.1.13 on 2026-09-22 13:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('kind', models.CharField(choices=[('milestone', 'Milestone'), ('craft', 'Craft'), ('community', 'Community'), ('stewardship', 'Stewardship')], default='milestone', max_length=16)),
                ('description', models.CharField(max_length=240)),
                ('criteria', models.CharField(help_text='Published on the badge. Say exactly how it is earned.', max_length=300)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('rank', models.PositiveSmallIntegerField(unique=True)),
                ('min_points', models.PositiveIntegerField()),
                ('min_confirmed_contributions', models.PositiveSmallIntegerField(default=0)),
                ('min_completed_projects', models.PositiveSmallIntegerField(default=0)),
                ('requires_teaching', models.BooleanField(default=False, help_text='Requires confirmed contributions in the mentorship dimension.')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('participation', 'Participation in a project'), ('completion', 'Completion of a delivered project'), ('mentorship', 'Mentorship'), ('community', 'Community contribution')], max_length=16)),
                ('recipient_name', models.CharField(max_length=160)),
                ('statement', models.TextField(max_length=1200)),
                ('verification_code', models.CharField(db_index=True, max_length=24, unique=True)),
                ('ledger_head', models.CharField(blank=True, help_text='The ledger hash at the moment of issue, tying the certificate to a point in the verifiable record.', max_length=64)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=300)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_points', models.PositiveIntegerField(db_index=True, default=0)),
                ('confirmed_contributions', models.PositiveIntegerField(default=0)),
                ('completed_projects', models.PositiveIntegerField(default=0)),
                ('projects_led', models.PositiveIntegerField(default=0)),
                ('people_mentored', models.PositiveIntegerField(default=0)),
                ('points_by_dimension', models.JSONField(blank=True, default=dict)),
                ('points_by_area', models.JSONField(blank=True, default=dict)),
                ('first_contribution_at', models.DateTimeField(blank=True, null=True)),
                ('last_contribution_at', models.DateTimeField(blank=True, null=True)),
                ('recomputed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holders', to='recognition.level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='standing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_points'],
            },
        ),
        migrations.CreateModel(
            name='BadgeAward',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('awarded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='recognition.badge')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge_awards', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'badge', 'project'), name='uniq_badge_award')],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('discipline', 'Discipline area'), ('community', 'Community contribution'), ('mentorship', 'Mentorship'), ('overall', 'Overall')], max_length=12)),
                ('period', models.CharField(choices=[('trimester', 'Trimester'), ('year', 'Year'), ('all_time', 'All time')], default='trimester', max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('rows', models.JSONField(default=list, help_text='[{rank, user_id, display_name, public_slug, points, contributions}]')),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discipline_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to='accounts.disciplinearea')),
            ],
            options={
                'ordering': ['-period_end', 'scope'],
                'constraints': [models.UniqueConstraint(fields=('scope', 'discipline_area', 'period', 'period_start'), name='uniq_leaderboard_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='LevelAward',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_at_award', models.PositiveIntegerField()),
                ('awarded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='recognition.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'level'), name='uniq_level_award')],
            },
        ),
    ]
