# Generated by Django 5.1.13 on 2026-09-23 07:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('downloaded_by_name', models.CharField(blank=True, help_text='Denormalised so the trail survives the account being erased.', max_length=160)),
                ('was_holder', models.BooleanField(default=True, help_text="False when a steward took a copy on the member's behalf.")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('downloaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='recognition.certificate')),
                ('downloaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-downloaded_at'],
                'indexes': [models.Index(fields=['certificate', '-downloaded_at'], name='recognition_certifi_ce623d_idx')],
            },
        ),
    ]
