# Generated by Django 5.1.13 on 2026-09-22 13:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import forge.common.fields
import forge.showcase.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseEntry',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=180, validators=[forge.common.fields.validate_no_html])),
                ('what_we_built', models.TextField(max_length=4000, validators=[forge.common.fields.validate_no_html])),
                ('what_we_learned', models.TextField(help_text='Including what went wrong. A showcase where every project went smoothly is a showcase nobody believes, and the difficulties are the most useful part for the next team.', max_length=4000, validators=[forge.common.fields.validate_no_html])),
                ('outcome', models.TextField(blank=True, help_text='Who used it, what changed, what happened next.', max_length=2000, validators=[forge.common.fields.validate_no_html])),
                ('demonstration_url', models.URLField(blank=True, help_text='A link to a short demonstration video hosted elsewhere. FORGE does not host video.', validators=[forge.showcase.validators.validate_video_url])),
                ('documentation_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('live_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('repository_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_note', models.CharField(blank=True, max_length=200)),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='showcase', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'showcase entries',
                'ordering': ['-is_featured', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ShowcaseImage',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='showcase/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(help_text="Describe the image for someone who cannot see it. Required: the University's inclusivity commitment applies to this platform as much as to any other.", max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='showcase.showcaseentry')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
