# Generated by Django 5.1.13 on 2026-09-22 13:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_label', models.CharField(blank=True, help_text="The actor's name as it stood at the time. Kept so that the log stays readable after an account is erased.", max_length=200)),
                ('action', models.CharField(choices=[('user.registered', 'Member registered'), ('user.email_verified', 'Email verified'), ('user.signed_in', 'Signed in'), ('user.sign_in_failed', 'Sign-in failed'), ('user.password_changed', 'Password changed'), ('user.deprovisioned', 'Account deprovisioned'), ('user.data_exported', 'Personal data exported'), ('user.data_erased', 'Personal data erased'), ('role.granted', 'Role granted'), ('role.revoked', 'Role revoked'), ('project.transitioned', 'Project changed stage'), ('project.reviewed', 'Proposal reviewed'), ('project.member_joined', 'Member joined a project'), ('project.member_left', 'Member left a project'), ('contribution.submitted', 'Contribution submitted'), ('contribution.attested', 'Contribution attested'), ('contribution.disputed', 'Contribution disputed'), ('ledger.appended', 'Ledger entry appended'), ('certificate.issued', 'Certificate issued'), ('certificate.revoked', 'Certificate revoked'), ('moderation.reported', 'Content reported'), ('moderation.action', 'Moderation action taken')], db_index=True, max_length=48)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, help_text='Null where the platform itself acted, for example a scheduled task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('target_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'audit event',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['action', 'occurred_at'], name='audit_audit_action_7e10a4_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__4eae27_idx')],
            },
        ),
    ]
