# Generated by Django 5.1.13 on 2026-09-22 13:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import forge.common.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimension', models.CharField(choices=[('delivery', 'Delivery -- work completed against an objective'), ('review', "Review -- checking and improving others' work"), ('documentation', 'Documentation -- writing it down for others'), ('mentorship', 'Mentorship -- teaching and supporting others'), ('community', 'Community -- answering, organising, moderating'), ('leadership', 'Leadership -- coordinating a team to a result'), ('research', 'Research -- investigation, field work, analysis'), ('design', 'Design -- interface, service or visual design')], db_index=True, max_length=16)),
                ('description', models.TextField(help_text="What you did, specifically enough that your lead and mentor can recognise it. 'Worked on the backend' is not a contribution record; 'built and tested the contribution ledger, including the hash chain' is.", max_length=2000, validators=[forge.common.fields.validate_no_html])),
                ('evidence_url', models.URLField(blank=True, help_text='A link to the work itself: a commit, a pull request, a document, a recording. Optional but it makes confirmation quick.', validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('effort_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Approximate. Used for your own record, not for ranking.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)])),
                ('occurred_on', models.DateField(default=django.utils.timezone.localdate)),
                ('ai_assistance', models.CharField(choices=[('none', 'No AI assistance'), ('assisted', 'AI-assisted, reviewed and understood by me'), ('generated', 'Substantially AI-generated, curated by me')], default='none', max_length=10)),
                ('ai_assistance_note', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Awaiting confirmation'), ('confirmed', 'Confirmed'), ('disputed', 'Disputed'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='workspace.milestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='projects.project')),
                ('skills_used', models.ManyToManyField(blank=True, related_name='contributions', to='accounts.skill')),
            ],
            options={
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attestor_name', models.CharField(max_length=160)),
                ('capacity', models.CharField(choices=[('lead', 'Project lead'), ('mentor', 'Mentor'), ('peer', 'Peer reviewer'), ('community_lead', 'Community lead')], max_length=16)),
                ('decision', models.CharField(choices=[('confirm', 'Confirmed'), ('dispute', 'Disputed')], max_length=8)),
                ('note', models.TextField(blank=True, max_length=1000, validators=[forge.common.fields.validate_no_html])),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('attestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attestations_given', to=settings.AUTH_USER_MODEL)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='contributions.contribution')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.BigIntegerField(editable=False, unique=True)),
                ('dimension', models.CharField(choices=[('delivery', 'Delivery -- work completed against an objective'), ('review', "Review -- checking and improving others' work"), ('documentation', 'Documentation -- writing it down for others'), ('mentorship', 'Mentorship -- teaching and supporting others'), ('community', 'Community -- answering, organising, moderating'), ('leadership', 'Leadership -- coordinating a team to a result'), ('research', 'Research -- investigation, field work, analysis'), ('design', 'Design -- interface, service or visual design')], db_index=True, max_length=16)),
                ('points', models.PositiveIntegerField(default=0, help_text='Recognition weight, computed at settlement. Frozen here so that a later change to the weighting cannot quietly rewrite what someone already earned.')),
                ('payload', models.JSONField(editable=False)),
                ('previous_hash', models.CharField(editable=False, max_length=64)),
                ('entry_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('contribution', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entry', to='contributions.contribution')),
                ('contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'ledger entries',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['contributor', 'status'], name='contributio_contrib_cc4945_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['project', 'status'], name='contributio_project_eba4af_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['dimension', 'status'], name='contributio_dimensi_18a287_idx'),
        ),
        migrations.AddConstraint(
            model_name='attestation',
            constraint=models.UniqueConstraint(fields=('contribution', 'capacity'), name='uniq_attestation_per_capacity'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['contributor', 'recorded_at'], name='contributio_contrib_3577d6_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['project', 'dimension'], name='contributio_project_219651_idx'),
        ),
    ]
