# Generated by Django 5.1.13 on 2026-09-22 18:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('template', models.CharField(max_length=60)),
                ('category', models.CharField(db_index=True, default='general', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Accepted by the mail server'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(blank=True, help_text='The member this concerned, where there was one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'email log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='common_emai_status_e24e32_idx')],
            },
        ),
    ]
